### ISSUE TITLE
[89EB] Omen Desktop: Not Compatible, Do Not Use

### ISSUE THREAD

**Issue by Rewinday** [OmenMon/OmenMon#73]
I installed OmenMon on a desktop by mistake. 

Now my fan are incontrollable and I don"t know how to pull back the original configuration... 
I reseted bios and windows and the fan curve is still messed up...

My mobo is a HP 89EB

**Comment by Mejval5** [comment]
Omg this happened to me as well.

Here is the fix for my PC:

1. Install Omen Gaming Hub and setup your fan profiles. Technically you can still use omenmon, but I don't trust it anymore.

2. Download OmenMon.exe and change these settings (some of them might be optional) in OmenMon.xml:

<BiosErrorReporting>false</BiosErrorReporting>
<FanCountdownExtendAlways>true</FanCountdownExtendAlways>
<FanCountdownExtendInterval>5</FanCountdownExtendInterval>
<FanLevelMax>5</FanLevelMax>
<FanLevelMin>0</FanLevelMin>
<FanLevelNeedManual>true</FanLevelNeedManual>
<FanLevelUseEc>true</FanLevelUseEc>
<FanProgramModeCheckFirst>false</FanProgramModeCheckFirst>
3. Open command line/powershell in same folder. The commands are essentially same. I use powershell. Open it in same folder as the exe.

4. Run:

.\OmenMon.exe -Bios

-> This shows you how many fans you have, I have two CPU and GPU

5. Run:

.\OmenMon.exe -Bios FanLevel=2,2

-> The 2s are the speed of fans, this will hard set the default to 2. It is very low but during startup your PC will not overheat I think, so all good. You can tweak it. If you have more than two or less, adjust amout of 2s. They should be separated commas. e.g. 3 fans - .\OmenMon.exe -Bios FanLevel=2,2,2

6. Go to Task Scheduler and delete OmenMon from the list (right click delete)

-> this prevents it from running on startup, also disable that in config or in the GUI.

This sets the default values for the fans to be quite low, so you really need to also control the fans after you login. The omen gaming hub is okay for this, so I use it. You might be able to actually use the omenmon by injecting the fan table using the command line. But it is kind of hard to understand.


At least you don't have to wipe your PC and it won't make crazy noises next time you launch it.

Also delete OmenMon from PC if you don't need it. On the other hand, if it is not in the Task Scheduler, it won't run so you can keep it in some folder for later use.

**Comment by GeographicCone** [comment]
> you can still use omenmon, but I don't trust it anymore

> delete OmenMon from PC if you don't need it

I fully support your right not to use _OmenMon_ but please do not spam this repository.

Uninstallation instructions are well-documented. The issues are open for productive contributions and informative discussions.

(The user in question also created a separate issue just to post the same comment over again.)

**Comment by Mejval5** [comment]
@GeographicCone

I found several people struggling with this issue on reddit and here as well.
If the instructions are well documented then where can we find them? I somehow doubt they cover the case I write here.

If you have a problem with me creating issue ticket that I made sure that others don't spend 5 hours fixing what OmenMon "broke" then at least write your reply to that ticket. Not to a a ticket in which I try to help someone else who fell in the same "hole".

**Comment by Mejval5** [comment]
So, you deleted my other ticket.. Great, what a great approach. You don't reply to problems of people for a year after your software broke their system. And when someone finally tries to help, you delete their helpful issue ticket and write "you are spamming repository".... Cmon

I respect that you helped/made a great piece of open source software, but please understand that it can really fk up people's computer and you should write my guide (or similar) to your readme because many people will have disfunctional devices afterwards.

**Comment by GeographicCone** [comment]
_OmenMon_ works great for me on my laptop model. I use it all the time on a daily basis.

I shared my complete solution on the odd chance it might be useful for others as well. And it does indeed seem to work for hundreds of other people with laptop models similar enough to mine.

With the help of the community, any bugs and issues were resolved. The application is feature-complete as is.

Of course, _OmenMon_ does not necessarily work on every _HP_-branded laptop out there, nor is it expected to. This is well-stated throughout the documentation.

**I am truly sorry _OmenMon_ does not work for you. Please accept my deepest apologies. But I never promised you it would.**

**The way I wrote _OmenMon_, it can be easily extended to work with your model as well. Nothing stops you from stepping up to do so.**

I already shared everything I learned about hardware control, and the full source code of the implementation under a permissible license. That makes you strictly better off than if you had to start from scratch.

> It can really fk up people's computer

No. _OmenMon_ only does exactly what it is told to do by the user, exactly as documented, and as seen in its _open_ source. "It" alone cannot mess up your computer, only _you_ yourself can – whether using _OmenMon_, or just as well without it, if you don't know what you're doing.

_OmenMon_ is intended for people looking to experiment. Just because it's available to you does not mean you have to install it. I certainly did not force you to use it. But if you do, you assume the responsibility, which is clearly stated, and should be obvious in any case.

Since you require an immediate solution without any hiccups, and are not willing to spend time configuring it, have you considered the possibility _OmenMon_ might really not be the best fit for your expectations?

When you cut yourself slicing bread, whose fault is it? IKEA?

If you can't handle a knife safely, perhaps you should just stick to buying sliced bread.

> Many people will have disfunctional devices afterwards

This is completely unsubstantiated. All it takes is a power cycle to clear any transient EC state. And you should not set it to start with Windows until the settings are well-tested, which is common sense.

However, do note that in the end, everyone is using _OmenMon_ at their own risk, as clearly stated.

> You don't reply to problems of people

I wrote extensive documentation, sharing literally _everything_ I know. If I forgot anything, the answer is ultimately in the _open_ source code. Still, I did reply to dozen of issue comments and posts, including elsewhere. Up to a point. However, repeatedly restating what's already been said for the benefit of people who can't be bothered to look for this information themselves is not the best use of anyone's time. Still:

**I sincerely apologize to each and every person I could not personally respond to regarding their use of the free software I made available to them.**

And I genuinely mean it. I wish I had more time to allocate to _OmenMon_, and I've always enjoyed responding to user feedback, but this is not the only thing I do in life.

> You should write my guide (or similar) to your readme

I truly can't believe your sense of entitlement. Who are you to tell me what I should or should not do? 

You've already got a lot from me, in exchange for nothing. Whether what you got is or isn't useful to you is _your_ problem, _not_ mine. I do not understand where the notion that I owe you anything else on top of all the stuff I have already given you comes from – but it's absurd.

> So, you deleted my other ticket.. Great, what a great approach.

Compatibility reports are grouped with one issue per model, as clearly stated. Most people still know how to search for information and they will search the issues for their model number. This keeps things organized.

In any case, copying and pasting exactly the same content all over again is not acceptable form of "discussion" just about anywhere. It beggars belief this has to be explained at all.

On top of that, general and counterfactual statements of opinion you have repeatedly made do not contribute any added value, and only decrease signal-to-noise ratio.

I left the issues open for a reason, and I am really reluctant to get involved. In general, I certainly do not object to someone having their opinion, whether I agree or disagree, or whether objectively right or wrong. However, there is a place for everything. And in this place, ultimately under my discretion, I determined that what I want to be posted is generally supposed to be helpful, and should stay organized. The duplicate post you purposefully made failed to meet either of these criteria, hence I deleted it.

----

**I am now feeling sorry to the numerous people who sent me genuinely helpful contributions, and I did not have the time to respond to them.** Yet in comparison, I am now forced to waste my time on this colossal nonsense to deal with the mess you are creating here. What is it that you want?

You think you've made a great discovery that _OmenMon_ does not work on your particular laptop, and that it also didn't work for someone else in the past. Guess what: nobody said it was supposed to, this is by design. It _might_ not work with what it was not designed for.

You are not contributing to _OmenMon_. You are not going to use it, and you have announced it to the world loud and clear. You were allowed to state your point however you wanted to – just not the same point more than once. You have now received a detailed response from me, and this is all I have to say to you. I would suggest it is time to move on.

Alternatively, feel free to tell the world this free utility is evil, ruined your life and ate your dog. I am certainly not going to stop you. You are free to do what you want, just not necessarily here – unless you fundamentally improve the quality of your contributions, which I doubt will happen. 

----

<ins>Edit</ins>: Only now did I realize this whole issue relates to _OmenMon_ being installed by accident **on a desktop**. Not even a laptop. It definitely should **not** be expected to work.

**Comment by Mejval5** [comment]
Hey,

I don't think it is evil. I didn't mean to come off like that.

On the contrary, the tool i super cool. And it seems to work perfectly on Laptops.

The issue is that several (at least 5 that I found online) PC users have serious problem with fans after testing it because the utility uploads code into the embedded controller and it forever changes the embedded controller logic.

For me, it changed the behavior of the embedded controller to ramp the fans to 100% for the first 10mins after starting PC, before the OS would finally calm them down to the curves I have set.

Maybe you could add a warning or part of my tutorial to your Readme, just to prevent some people having issues in the future.

Just one comment:

> You've already got a lot from me, in exchange for nothing. Whether what you got is or isn't useful to you is your problem, not mine. I do not understand where the notion that I owe you anything else on top of all the stuff I have already given you comes from – but it's absurd.

I really don't think you can say this. Yes, open source doesn't entitle me to something that works, but you also did slightly break some people's machine with the promise of making them better. Putting a small warning into the readme would be definitely nice thing to do.

**Comment by Mejval5** [comment]
I also wrote to the main reddit post that comes up with google search.

Not to spite you, but to help others. If I reply to their comment then Reddit notifies them.

https://www.reddit.com/r/HPOmen/comments/17oet58/omenmon_fan_gpu_keyboard_performance_monitoring/


> This is completely unsubstantiated. All it takes is a power cycle to clear any transient EC state. And you should not set it to start with Windows until the settings are well-tested, which is common sense.

This is simply not true. I have a desktop PC and power cycles did not fix it. Even leaving it turned off overnight didn't fix it. Maybe unplugging it and draining all electricity from capacitors (by pressing power button) could do it. I didn't try that to be fair, but it's not really something many people know to do.

**Comment by GeographicCone** [comment]
Here we go for the third time – and yet again you just couldn't be bothered to edit your previous post (or, even better, write everything you want it to say from the start), as opposed to spamming additional replies:

> The utility uploads code into the embedded controller and it forever changes the embedded controller logic.

This is utter gibberish. What you wrote doesn't even make sense. You simply do not know what you are trying to talk about.

Regardless of all the nonsense I have no intention to sift through any further, let me reiterate that **_nothing_ is being changed permanently**. I would know, since I wrote this utility. Of course you don't have to trust what I am saying but what is then the point of trying to discuss it with me? Again, it's all in the _open_ source: if you don't believe me, check for yourself.

> Maybe you could add a warning or part of my tutorial to your Readme [...]

What you are demanding is already in the description on the front page:

> OmenMon is a lightweight application that interacts with the Embedded Controller (EC) and WMI BIOS routines of an HP Omen <ins>**laptop**</ins>

It follows from common logic that if you have a **desktop**, not a laptop, then this software is not for you. If it somehow works (which I believe it partially does, while being careful) – great. But if it doesn't, do not bother anyone else, especially me, with your unreasonable complaints.

Further from the description:

> Most features are specific to HP devices with a compatible BIOS interface [...] <ins>**The software is provided as-is and comes with no warranty. The user solely assumes all responsibility arising from its use.**</ins>

So the warning is already there. Too bad you didn't heed it but there's nothing I can do on my part, short of taking down the whole repository in case someone incompetent stumbles upon it and does something stupid with the tool that <ins>has a very specific use case that might or might not be fit for your situation</ins>.

> I have a desktop PC 

You want me to add a warning that this _laptop_ utility is not made for _desktops_? Should the proposed warning also then state it's not for _HP_ printers or calculators (if they still make them) either? Should it then also say it's not for, say, _Asus_ or _Dell_ laptops? Should it list all computer devices in the world it is not compatible with? Starting from the _ZX Spectrum_ or what?

Seriously, everything you need to know is already there – if you bothered to read it. I do not understand your "tutorial" so I doubt others would but to the extent that I can see, it tells people how to stop _OmenMon_ from starting with Windows. This, and everything else, is already covered in the documentation, in particular at: https://omenmon.github.io/cli#task

> I also wrote to the main reddit post that comes up with google search. Not to spite you, but to help others. If I reply to their comment then Reddit notifies them.

Sure, everything you're doing here is clearly "to help others" and definitely "not out of spite" that you did something unreasonable, and had to clean up after yourself. Whatever. By all means take it to Reddit you seem to be implicitly threatening me with, or anywhere else if you feel that is the best use of your time. I, on the other hand, have better things to do.

I had not blocked you outright but by repeatedly acting like this you are leaving me no choice. Enough is enough, and we're done here. Best of luck.
